### ISSUE TITLE
Lecture 3 Exercise 2.1 answer boxes have a 5 character cap but address answers are 6 characters long

### ISSUE THREAD

**Issue by DrewDame** [jamesjuett/eecs280-async-lectures#16]
In lecture 3 exercise 2.1, the address answers (ptr, &x, etc.) are 6 characters long but seem to have a 5 character max
![image](https://github.com/jamesjuett/eecs280-async-lectures/assets/133512353/e1969838-7ed5-4e8e-a402-cd50bf36899d)
https://lobster.eecs.umich.edu/async-lecture/3/lec3.html

**Comment by jamesjuett** [comment]
Fixed! Thanks for pointing this out.
