### ISSUE TITLE
Inheritance lecture missing an excercise

### ISSUE THREAD

**Issue by majosh-1** [jamesjuett/eecs280-async-lectures#17]
I'm using chrome on MacOS
As said in title, it is more specifically a 404 error not found, this is for learning how to delegate constructors
<img width="846" alt="Screenshot 2023-09-26 at 12 09 23 PM" src="https://github.com/jamesjuett/eecs280-async-lectures/assets/118770405/b07324f9-5cd5-4867-ad3e-0b97c7f4f140">

**Comment by jamesjuett** [comment]
Fixed via 9114923, thanks for reporting this!
